name: Android Build APK

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v0.*'
  workflow_dispatch: # لتشغيل البناء يدوياً من تبويب Actions في أي وقت

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK (Unsigned / Release)
        run: ./gradlew assembleLatestUniversalRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Jaziri-Player-APK
          path: app/build/outputs/apk/latestUniversal/release/*.apk
